name: QA
on: 
  pull_request:
  workflow_dispatch:  
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.11.0 # version used by Vercel

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm --version && pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Validate paths
        env:
          SALEOR_API_URL: https://master.staging.saleor.cloud/graphql/
        run: |
          pnpm --filter=storefront paths
          pnpm prettier --write ./apps/storefront/lib/\$path.ts
          git diff --exit-code ./apps/storefront/lib/\$path.ts

      - name: Check linters
        run: pnpm run lint

      - name: Check TypeScript
        run: pnpm run check-types
